### ISSUE TITLE
Python branch is broken

### ISSUE THREAD

**Issue by Mikaela** [jreese/znc-push#164]
```
-rw-r--r-- 1 mikaela users 47K Jun  4 20:56 /home/users/mikaela/.local/lib/znc/push.py
```

I update modules when I update ZNC and I only download the module files, but as there haven't been commits lately, I think this is the latest version.

```
2015-06-07 09:02:07+0300 < *status> Unable to find modinfo [push] [Traceback (most recent call last):
2015-06-07 09:02:07+0300 < *status>   File "/home/users/mikaela/.local/lib/znc/modpython/znc.py", line 644, in get_mod_info
2015-06-07 09:02:07+0300 < *status>     pymodule, datadir = find_open(modname)
2015-06-07 09:02:07+0300 < *status>   File "/home/users/mikaela/.local/lib/znc/modpython/znc.py", line 510, in find_open
2015-06-07 09:02:07+0300 < *status>     pymodule = imp.load_module(modname, *x)
2015-06-07 09:02:07+0300 < *status>   File "/home/users/mikaela/.local/lib/znc/push.py", line 1512
2015-06-07 09:02:07+0300 < *status>     e_unknown_service = 'Sorry, push service {0} not supported'
2015-06-07 09:02:07+0300 < *status>    ^
2015-06-07 09:02:07+0300 < *status> IndentationError: unexpected indent
2015-06-07 09:02:07+0300 < *status> ]
```

**Comment by Mikaela** [comment]
It looks like I have forgotten

```
2015-06-09 16:17:44+0300 < *status> ZNC 1.7.x-git-191-8552ca0 - http://znc.in
2015-06-09 16:17:44+0300 < *status> IPv6: yes, SSL: yes, DNS: threads, charset: yes
```

**Comment by jreese** [comment]
Is this still a problem?  I was able to load push on a fresh build from znc master without an error.

**Comment by Mikaela** [comment]
I have no idea as I haven't been using the module since I moved to Jolla as no notification service supports Sailfish OS. Having seen more people load it without issues this probably isn't an issue anymore, but you saw https://github.com/jreese/znc-push/issues/165 reproduced yesterday too.
